// flow-typed signature: 97d6fd72413b8e95ad7c212995ae682d
// flow-typed version: <<STUB>>/mobx-react-lite_v^1.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react-lite/dist/custom' {
  declare module.exports: any;
}

declare module 'mobx-react-lite/dist/custom.module' {
  declare module.exports: any;
}

declare module 'mobx-react-lite/dist/index' {
  declare module.exports: any;
}

declare module 'mobx-react-lite/dist/index.min' {
  declare module.exports: any;
}

declare module 'mobx-react-lite/dist/index.module' {
  declare module.exports: any;
}

declare module 'mobx-react-lite/dist/native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react-lite/dist/custom.js' {
  declare module.exports: $Exports<'mobx-react-lite/dist/custom'>;
}
declare module 'mobx-react-lite/dist/custom.module.js' {
  declare module.exports: $Exports<'mobx-react-lite/dist/custom.module'>;
}
declare module 'mobx-react-lite/dist/index.js' {
  declare module.exports: $Exports<'mobx-react-lite/dist/index'>;
}
declare module 'mobx-react-lite/dist/index.min.js' {
  declare module.exports: $Exports<'mobx-react-lite/dist/index.min'>;
}
declare module 'mobx-react-lite/dist/index.module.js' {
  declare module.exports: $Exports<'mobx-react-lite/dist/index.module'>;
}
declare module 'mobx-react-lite/dist/native.js' {
  declare module.exports: $Exports<'mobx-react-lite/dist/native'>;
}
